### ISSUE TITLE
How can I pass a vector from rust to swift data ?

### ISSUE THREAD

**Issue by daoan1412** [thombles/dw2019rust#1]
How can I pass a vector from rust to swift data ?

**Comment by thombles** [comment]
It depends on some circumstances:
* Does Swift call Rust which _returns_ a vector, or does Rust call Swift with a vector _argument_?
* Do we allocate the memory on the Rust side or the Swift side?

Here's an example where Swift is calling Rust, Rust is returning a vector, and Rust is providing the memory allocation:

```rust
#[no_mangle]
pub extern "C" fn provide_array_of_ints(len: *mut c_uint) -> *mut i8 {
    let my_vec: Vec<u8> = vec![1, 2, 3, 4];
    let slice = my_vec.into_boxed_slice();
    unsafe {
        *len = slice.len() as c_uint;
    }
    Box::into_raw(slice) as *mut i8
}

#[no_mangle]
pub extern "C" fn free_array(arr: *mut i8) {
    drop(unsafe { Box::from_raw(arr) });
}
```

Generated C header:
```c
int8_t *provide_array_of_ints(unsigned int *len);
void free_array(int8_t *arr);
```

Swift:
```swift
var len: UInt32 = 0
let arrayPtr = provide_array_of_ints(&len)
print("Length: \(len)")
let array = Array(UnsafeBufferPointer(start: arrayPtr, count: Int(len)))
free_array(arrayPtr)
print("Array: \(array)")
```

Swift Output:
```
Length: 4
Array: [1, 2, 3, 4]
```

Take care that if you allocate any Boxes in Rust you need to free them in Rust, and if you allocate any UnsafeMutablePointers in Swift you need to free them in Swift.

**Comment by daoan1412** [comment]
Your answer solves my problem. Thank you so much!

**Comment by thombles** [comment]
Glad to help!
