### ISSUE TITLE
Giving some errors while checking run compatibility for c and swift on m1 mac

### ISSUE THREAD

**Issue by HakanKumdakci** [thombles/dw2019rust#3]
I've followed the guide but it gives this output with command
 `nm target/debug/libanvil.a | grep hello`
```
0000000000000000 T _hello_devworld
target/debug/libanvil.a:rustc_std_workspace_alloc-9cf27ed549592a86.rustc_std_workspace_alloc.9703e405-cgu.0.rcgu.o: no symbols
target/debug/libanvil.a:cfg_if-718033b8fe200c22.cfg_if.ecdc0997-cgu.0.rcgu.o: no symbols
target/debug/libanvil.a:rustc_std_workspace_core-b5600cb14c277fae.rustc_std_workspace_core.3407a808-cgu.0.rcgu.o: no symbols
```

I ignored it but when I run with iOS app it gives this error
```
Undefined symbols for architecture arm64:
  "_hello_devWorld", referenced from:
      ExampleRustApp.ViewController.viewDidLoad() -> () in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've installed rust with rustup instead of homebrew. My rustup show command give this output
```
Default host: aarch64-apple-darwin
rustup home:  /Users/hakan/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
x86_64-apple-ios

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Comment by thombles** [comment]
I can see a typo there. Your library is exporting `_hello_devworld` but your iOS app is looking for `_hello_devWorld` with a capital `W`. Try making those match!

I don't have an M1 Mac so there might be some differences or problems. If you run into anything that deserves an update feel free to make a PR. This tutorial will be more useful if it keeps up with the times.

**Comment by HakanKumdakci** [comment]
Oh, couldn't realize that typo, thanks a lot.
