### ISSUE TITLE
Please update the tutorial

### ISSUE THREAD

**Issue by ssrlive** [thombles/dw2019rust#5]
Please update the tutorial and revise the "Automated Build" section to use the [cargo-lipo](https://crates.io/crates/cargo-lipo) tool instead.

This will result in fewer steps and a simpler process.

And [here is my template](https://github.com/ssrlive/rust_on_android_ios#prepare).

**Comment by thombles** [comment]
Thanks for bringing it to my attention. I think I will leave it as-is. The goal of this tutorial is to build an understanding of how Rust and iOS code fits together, which is best served by building and working with the artifacts for different architectures manually. A different kind of tutorial might try to make it as quick and seamless as possible.

Separately, FYI the readme for `cargo-lipo` says that it's "deprecated/passively maintained" so I wouldn't necessarily recommend it for new projects.
